version: '3.7'
services:
  web:
    image: nginx:latest
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./config/nginx/sites-enabled/default.conf:/etc/nginx/sites-enabled/default.conf
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./config/nginx/ssl:/etc/nginx/ssl
      - ./config/nginx/auth:/etc/nginx/auth
      - type: volume
        source: app_data
        target: /var/www/html
    links:
      - php
    networks:
      - front
      - back

  php:
    image: php:7.2-fpm-alpine
    expose:
      - 9000
    build:
      context: ./src
      dockerfile: Dockerfile
      args:
        - ENVIROMENT=${ENVIROMENT}
    volumes:
      - ./config/php/php.ini:/usr/local/etc/php/php.ini
      - ./config/php/php-fpm.conf:/usr/local/etc/php-fpm.conf
      # - ./config/php/ext-xdebug.ini:/usr/local/etc/php/conf.d/ext-xdebug.ini
      - type: volume
        source: app_data
        target: /var/www/html
    env_file: .env
    depends_on:
      - appdata
      - mysql
      - cache
    user: www-data
    networks:
      - back
  
  appdata:
    image: php:7.2-fpm-alpine
    volumes: 
      - ./config/appdata/startup.sh:/startup.sh
      - type: volume
        source: app_data
        target: /var/www/html
    command: /bin/sh /startup.sh

  mysql:
    image: mysql:5.7
    env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - magento2mysqldata:/var/lib/mysql
    networks:
      - back

  cache:
    image: redis:latest
    networks:
      - back

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: "mysql"
      PMA_PORT: 3306
    networks:
      - front
      - back

volumes:
  magento2mysqldata:
    driver: local
  app_data:
    driver: local
    driver_opts:
      type: none
      device: "${ROOT_PROJECT}src"
      o: bind

networks:
  front:
    driver: bridge
  back:
    driver: bridge
